### ISSUE TITLE
Minimize dependencies

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-operator#387]
We have seen problems setting up new cloud environment - they did not start because GHCR was down. Can we avoid this?

**Comment by rymsha** [comment]
blocked by #388

**Comment by rymsha** [comment]
Operator itself does have dependencies on GHCR, Google Artifact Registry, Docker hub or anything similar.
With #388 it is also less severe if container registry used is down - as long as image is cashed by internal cluster container registry there will be no downtime.
