### ISSUE TITLE
GKE Autopilot restricts privileged mode

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp-operator#454]
https://discuss.enonic.com/t/kubernetes-operator-cluster-config-mount-issue/3028

In a GKE Autopilot mode cluster, the `configure-sysctl` init container operates in a privileged mode, which is restricted. To address this, we need to change the XP docker image by adding the 'vm.max_map_count=262144' value to the /etc/sysctl.conf file, which is a [recommended](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) configuration. Consequently, we can remove the init container.

**Comment by rymsha** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by rymsha** [comment]
DaemonSet `echo 262144 > /proc/sys/vm/max_map_count` should do the trick
