### ISSUE TITLE
Add a tag to domains in Cloudflare 

### ISSUE THREAD

**Issue by danhul** [enonic/xp-operator#544]
Having tags in cloudflare domain will helps us to easily identify which domain belongs to which service. 
Can tags be added by the operator when creating domains?

**Comment by vbradnitski** [comment]
1) As I can see, we have a "heritage" TXT record for every usual DNS Record. Won't it be enough?
2) Do you want to have the tag only on the main record or the heritage one as well?
3) How/where do you want to set them?
