### ISSUE TITLE
Liveness Readyness probes

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-operator#65]
Umbrella ticket to discuss and implement liveness/readyness probes correctly because current approach with app-alive
 doesn't work well.

Current problems
- app-alive reports "ready" too early : when Elasticsearch still replicates shards (yellow). It leads do data loses during rolling update.

- app-alive reports "not alive" on ALL nodes, just because Elasticsearch cluster lost its master due to its restart. Currently it is XP bug, but we still seek for better "alive" check than "es cluster is not red"

**Comment by vbradnitski** [comment]
HealthCheck endpoint: https://github.com/enonic/xp/issues/9199
